# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z010clg225-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/goma/Documents/Work/AES/RUN/AES/AES.cache/wt [current_project]
set_property parent.project_path /home/goma/Documents/Work/AES/RUN/AES/AES.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/goma/Documents/Work/AES/RUN/AES/AES.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/goma/Documents/Work/AES/invSubBytes.v
  /home/goma/Documents/Work/AES/timing_tester.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/goma/Documents/Work/AES/RUN/AES/AES.srcs/constrs_1/new/constraint.xdc
set_property used_in_implementation false [get_files /home/goma/Documents/Work/AES/RUN/AES/AES.srcs/constrs_1/new/constraint.xdc]


synth_design -top timing_tester -part xc7z010clg225-1


write_checkpoint -force -noxdef timing_tester.dcp

catch { report_utilization -file timing_tester_utilization_synth.rpt -pb timing_tester_utilization_synth.pb }
